"""
api.py - FastAPI Backend Service for Self-Correcting RAG
=========================================================

Exposes a POST endpoint /api/chat that accepts a QueryRequest
and returns the full grounded answer along with verified citations payload.

Author: Antigravity AI Pair Programmer
OS: Windows | Runtime: Python 3.13
"""

import sys
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uvicorn

# Reconfigure stdout to UTF-8 to prevent encoding crashes on Windows consoles
try:
    sys.stdout.reconfigure(encoding='utf-8')
except Exception:
    pass

# Import the self-correcting RAG pipeline runner
from self_correcting_rag import run_pipeline

# Initialize FastAPI application
app = FastAPI(
    title="Self-Correcting Agentic RAG API",
    description="FastAPI Backend for 4th-Sem B.Tech AI Project",
    version="1.0.0"
)

# Configure CORS Middleware to allow all origins
# This ensures that future local React development servers can query the backend without CORS blocks
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Define Pydantic request schema
class QueryRequest(BaseModel):
    question: str

# Define POST endpoint at /api/chat
@app.post("/api/chat")
async def chat_endpoint(request_data: QueryRequest):
    """
    POST endpoint to interact with the Self-Correcting RAG pipeline.
    Accepts JSON body: { "question": "..." }
    Returns the exact JSON payload dictionary generated by the pipeline:
    {
      "answer": "...",
      "citations": [ { "sentence": "...", "chunk_id": "..." }, ... ]
    }
    """
    question = request_data.question.strip()
    if not question:
        raise HTTPException(status_code=400, detail="Question cannot be empty.")
    
    try:
        # Execute the LangGraph pipeline
        result = run_pipeline(question)
        return result
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"An error occurred while executing the RAG pipeline: {str(e)}"
        )

# Run server using Uvicorn
if __name__ == "__main__":
    print("\nStarting Uvicorn server on http://0.0.0.0:8000 ...")
    uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=False)
    
# NOTE: Set reload=False so that loading heavy sentence-transformers / PyTorch models
# inside memory does not double-trigger or get interrupted during dynamic reloading.
