[project]
python_version = "3.13"
python_platform = "windows"
python_interpreter = "C:\\Users\\Darshan Karna\\OneDrive - sxc.edu.np\\Desktop\\4th sem project\\venv\\Scripts\\python.exe"
search_path = [
    "C:\\Users\\Darshan Karna\\OneDrive - sxc.edu.np\\Desktop\\4th sem project\\venv\\Lib\\site-packages",
]
